apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kuttleio/k8s-apps.git
    targetRevision: HEAD
    path: manifests/voting-app/dev
   
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true