---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app
