apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: voting-app
spec:
  generators:
  - git:
      repoURL: https://github.com/kuttleio/k8s-apps.git
      revision: HEAD
      directories:
      - path: voting-app/dir-generator/kuttle-project/*
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      project: default
      source:
        repoURL: https://github.com/kuttleio/k8s-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
        
